### ISSUE TITLE
NPE occurs in UMLOperationBodyMapper.findReplacementsWithExactMatching()

### ISSUE THREAD

**Issue by onewhl** [JetBrains-Research/kotlinRMiner#20]
[Commit](https://github.com/JetBrains-Research/codetracker/commit/f137fb956c6eca4fba16073470f6d1fa74350fdd)
`java.lang.NullPointerException
	at java.base/java.util.HashMap.putMapEntries(HashMap.java:496)
	at java.base/java.util.LinkedHashMap.<init>(LinkedHashMap.java:384)
	at org.jetbrains.research.kotlinrminer.decomposition.UMLOperationBodyMapper.findReplacementsWithExactMatching(UMLOperationBodyMapper.java:1085)
	at org.jetbrains.research.kotlinrminer.decomposition.UMLOperationBodyMapper.processLeaves(UMLOperationBodyMapper.java:257)
	at org.jetbrains.research.kotlinrminer.decomposition.UMLOperationBodyMapper.<init>(UMLOperationBodyMapper.java:112)
	at org.jetbrains.research.kotlinrminer.diff.UMLClassBaseDiff.updateMapperSet(UMLClassBaseDiff.java:1121)
	at org.jetbrains.research.kotlinrminer.diff.UMLClassBaseDiff.checkForOperationSignatureChanges(UMLClassBaseDiff.java:1028)
	at org.jetbrains.research.kotlinrminer.diff.UMLClassBaseDiff.process(UMLClassBaseDiff.java:85)
	at org.jetbrains.research.kotlinrminer.uml.UMLModel.diff(UMLModel.java:106)
	at org.jetbrains.research.kotlinrminer.api.GitHistoryRefactoringMiner.detectRefactorings(GitHistoryRefactoringMiner.java:72)
	at org.jetbrains.research.kotlinrminer.api.GitHistoryRefactoringMiner.detectAtCommit(GitHistoryRefactoringMiner.java:33)
	at TestAllRefactorings.testCommit(TestAllRefactorings.java:50)
`

**Comment by onewhl** [comment]
Fixed
